config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  unauthenticated do
    root to: "home#homepage"
  end
  authenticated :user do
    root to: "home#dashboard", as: :authenticated_root
  end
    

  get 'home/following', as: :following 

  get 'home/about', as: :about

  get 'home/userlist', as: :userlist
  
  get 'profile/:id' => 'home#profile', as: :profile
  
  get 'followers/:id' => 'home#follower', as: :follower

  resources :follows

  resources :statuses
  
  match 'poststatus' => 'statuses#poststatus', :via => [:post], :as => 'poststatus'
  
  match 'follow' => 'home#follow', :via=>[:post],:as =>'followuser'
  match 'unfollow' => 'home#unfollow', :via=>[:post],:as =>'unfollowuser'
  

  devise_for :users

end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :user, foreign_key: "following_id"
  
end

app/models/status.rb
class Status < ActiveRecord::Base
  
  belongs_to :user
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :statuses
  has_many :follows
  
  acts_as_taggable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
 protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:email, :password) }
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :profile_picture, :username, :date_of_birth, :email, :password, :password_confirmation) }
        devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name, :lasst_name, :profile_picture, :username, :tag_list, :date_of_birth, :email, :password, :password_confirmation, :current_password) }
end
        
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :set_follow, only: [:show, :edit, :update, :destroy]

  def index
    @follows = Follow.all
    
  end

  def show
    
  end

  def new
    @follow = Follow.new
    
  end

  def edit
  end

  def create
    @follow = Follow.new(follow_params)
    respond_to do |format|
    if @follow.update(follow_params)
      format.html {redirect_to @follow,notice:'Follow was successfully updated'}
      format.json {render :show,follow:ok, location:follow}
    else
      format.html {render:edit}
      format.json {render json: @follow.errors, follow:unprocessable_entity}
    end
  end   
    
  end

  def update
    @follow.update(follow_params)
     @follow.update(follow_params)
    respond_to do |format|
     if @follow.update(follow_params)
       format.html {redirect_to @follow,notice:'Follow was successfully updated'}
       format.json {render :show,follow:ok, location:follow}
    else
      format.html {render:edit}
       format.json {render json: @follow.errors, follow:unprocessable_entity}
    end
  end    
  end

  def destroy
    @follow.destroy
    @follow.destroy
     respond_to do |format|
       format.html {redirect_to follows, notice:'Follow was successfully destroyed'}
      format.json {head:no_content}
      
  end
    
  end

  private
    def set_follow
      @follow = Follow.find(params[:id])
    end

    def follow_params
      params.require(:follow).permit(:follower_id, :following_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def homepage
    
    @statuses=Status.all.order('id desc')    
    
  end
  
  def follow
    @addfollow=Follow.create(:follower_id=>params[:follower_id],:following_id=>params[:following_id])
  end
  
  def unfollow
    @removefollow=Follow.destroy_all(:follower_id=>params[:follower_id],:following_id=>params[:following_id])
  end

  def about
  end

  def dashboard
    @peopleifollow=Follow.where(:follower_id=>current_user.id)
    @id_peopleifollow=@peopleifollow.collect {|f| f["following_id"]}
    @id_peopleifollow=@id_peopleifollow.push(current_user.id)
    @statuses=Status.where('user_id in(?)',@id_peopleifollow).order("id desc")
  end

  def userlist
    @users=User.all
  end

  def profile
    
    @profile=User.find(params[:id])
    
  end

  def follower
    @profile=User.find(params[:id])
    @followers=Follow.where(:following_id=>params[:id]),joins("INNER JOIN users ON users.id=follows.follower_id")
  end

  def following
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  def poststatus
    @createstatus=Status.create(:user_id=>params[:user_id],:text=>params[:status][:text])
  end
  
  
  
  def index
    @statuses = Status.all
  end

  def show
  end

  def new
    @status = Status.new
  end

  def edit
  end

  def create
    @status = Status.new(status_params)
   respond_to do |format|
    if @status.update(status_params)
      format.html {redirect_to @status,notice:'Status was successfully updated'}
      format.json {render :show,status:ok, location:status}
    else
      format.html {render:edit}
      format.json {render json: @status.errors, status:unprocessable_entity}
    end
  end    
  end

  def update
    @status.update(status_params)
    respond_to do |format|
     if @status.update(status_params)
       format.html {redirect_to @status,notice:'Status was successfully updated'}
       format.json {render :show,status:ok, location:status}
    else
      format.html {render:edit}
       format.json {render json: @status.errors, status:unprocessable_entity}
    end
  end    
  end

  def destroy
    @status.destroy
     respond_to do |format|
       format.html {redirect_to statuses_url, notice:'Status was successfully destroyed'}
      format.json {head:no_content}
      
  end
  end

  private
    def set_status
      @status = Status.find(params[:id])
    end

    def status_params
      params.require(:status).permit(:text, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/follows/_form.html.erb
<%= form_for(@follow) do |f| %>
  <% if @follow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@follow.errors.count, "error") %> prohibited this follow from being saved:</h2>

      <ul>
      <% @follow.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :follower_id %><br>
    <%= f.number_field :follower_id %>
  </div>
  <div class="field">
    <%= f.label :following_id %><br>
    <%= f.number_field :following_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/follows/edit.html.erb
<h1>Editing follow</h1>

<%= render 'form' %>

<%= link_to 'Show', @follow %> |
<%= link_to 'Back', follows_path %>

app/views/follows/index.html.erb
<h1>Listing follows</h1>

<table>
  <thead>
    <tr>
      <th>Follower</th>
      <th>Following</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @follows.each do |follow| %>
      <tr>
        <td><%= follow.follower_id %></td>
        <td><%= follow.following_id %></td>
        <td><%= link_to 'Show', follow %></td>
        <td><%= link_to 'Edit', edit_follow_path(follow) %></td>
        <td><%= link_to 'Destroy', follow, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Follow', new_follow_path %>

app/views/follows/new.html.erb
<h1>New follow</h1>

<%= render 'form' %>

<%= link_to 'Back', follows_path %>

app/views/follows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Follower:</strong>
  <%= @follow.follower_id %>
</p>

<p>
  <strong>Following:</strong>
  <%= @follow.following_id %>
</p>

<%= link_to 'Edit', edit_follow_path(@follow) %> |
<%= link_to 'Back', follows_path %>

app/views/home/_statusbox.html.erb
<%@status = Status.new%>
<%=form_for @status,:url => url_for(:action => 'poststatus', :controller => 'statuses', :user_id=>current_user.id), :method => 'post', :remote => true do |f| %>
<%= f.label :text %><br>
<%= f.text_field :text,:id=>'statusinput' %>

<div class="actions">
  <%= f.submit "Post", :class=>"btn btn-info"%>
</div>
<%end%>

app/views/home/about.html.erb
<h1>About status updater</h1>
<p>Status updater allows you to follow status updates of people you are interested in.</p>

app/views/home/dashboard.html.erb
<h1>Dashboard</h1>
<p>Here are the updates for the people you follow</p>

<ul>
  <%@statuses.each do |status|%>
  <li><%=status.text%> - @<%=status.user.username%> (<%= time_ago_in_words(status.created_at) %> ago)</li>
  <%end%>
</ul>

app/views/home/follow.js.erb
location.reload();

app/views/home/follower.html.erb
<h1>
  <%= @profile.username%>'s Followers
</h1>
<p><%= link_to "Back to Profile", profile_path(@profile)%></p>


<ul>
  <%=@followers.each do |follower| %>
  <li><%=link_to follower.user.username, profile_path(follower.user)%></li>
  <%end%>
</ul>

app/views/home/following.html.erb
<h1>Home#following</h1>
<p>Find me in app/views/home/following.html.erb</p>

app/views/home/homepage.html.erb
<h1>Recent Statuses</h1>
</p>Here are the most recent statuses</p>

<ul>
  <% @statuses.each do |status| %>
  <li><%=status.text%> - @<%=status.user.username %> (<%= time_ago_in_words(status.created_at) %> ago)</li>
  <%end%>
</ul>

app/views/home/profile.html.erb
<h1><%= @profile.username%>'s profile</h1>
<h3>tags: <%= @profile.tag_list%></h3>
<h3><%= link_to "followers", follower_path(@profile) %></h3>

<%if not @profile.id == current_user.id%>
    <% @isuserfollowing= Follow.where(:follower_id=>current_user.id, :following_id =>@profile.id).count%>
     <% if @isuserfollowing == 0 %>



<%=form_tag(url_for(controller:'home', action:'follow',:follower_id=>current_user.id,:following_id=>@profile.id), method: :post, remote: true) do |f| %>
<%= button_tag("Follow",type:'submit',:class=>"btn btn-success")%>
<%end%>




<%else%>

<%=form_tag(url_for(controller:'home', action:'unfollow',:follower_id=>current_user.id,:following_id=>@profile.id), method: :post, remote: true) do |f| %>
<%= button_tag("Unfollow",type:'submit',:class=>"btn btn-danger")%>
<%end%>



<%end%>
<%end%>







<hr>
<%if @profile.id == current_user.id%>
<%= render 'home/statusbox'%>
<%end%>

<ul id="updates">
  <%@profile.statuses.order("id desc").each do |status| %>
  <li><%= status.text %></li>
  <%end%>
</ul>

app/views/home/unfollow.js.erb
location.reload();

app/views/home/userlist.html.erb
<h1>Users</h1>

<ul>
  <% @users.each do |user|%>
  <li><h3> <%= link_to user.username,profile_path(user)%></h3></li>
  <%end%>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Andrewsnetwork</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  
  
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Andrew's Network</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_url %></li>
        <% if user_signed_in? %>
        <li><%= link_to "Profile", profile_path(current_user) %></li>
        <li><%= link_to "All users", userlist_path %></li>
        <li><%= link_to "Settings", edit_user_registration_path %></li>
        <li><%= link_to "Log out", destroy_user_session_path, :method=>:delete %></li>
        
        <%else%>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Sign in", new_user_session_path %></li>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
        <%end%>
        
      </ul>
     
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

  <div class="container">
<%= yield %>
  </div>

</body>
</html>

app/views/statuses/_form.html.erb
<%= form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<h1>Listing statuses</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td><%= status.text %></td>
        <td><%= status.user_id %></td>
        <td><%= link_to 'Show', status %></td>
        <td><%= link_to 'Edit', edit_status_path(status) %></td>
        <td><%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Status', new_status_path %>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/poststatus.js.erb
$("#updates").prepend('<li><%=@createstatus.text%></li>');

$("#statusinput").val('');

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @status.text %>
</p>

<p>
  <strong>User:</strong>
  <%= @status.user_id %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>